echo "Starting chrome nodes"
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
docker run -d --link selenium-hub:hub selenium/node-chrome:2.44.0
echo "Starting firefox nodes"
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0
docker run -d --link selenium-hub:hub selenium/node-firefox:2.44.0

echo "Done, nodes are started and available on the grid"